"""Conteúdo das páginas de serviço geradas a partir de src/_servico.html (PT-PT, sem travessões, sem promessas de prazo).
Só factos confirmados pelo dono (AUDIT.md §0, STRATEGY.md §6).
Bombas de calor: águas quentes e sistemas combinados águas quentes + aquecimento (confirmado pelo dono a 28/09/2026). Radiadores e piso radiante não foram confirmados em separado: não os nomear. Marcas: MIDEA, Mitsubishi Electric, Daikin, France Air.
No texto visível, "ar-\u2060água" leva um word joiner (U+2060, invisível) depois do hífen para o título não partir em "ar-" / "água".
A Geist não tem o hífen inseparável U+2011 (o browser iria buscá-lo a outra fonte). Em title, desc, service_type, offers e alt fica o hífen simples."""

SERVICES = {
 'bombas-de-calor-lisboa': dict(
  nav='Bombas de calor', servico='Bomba de calor', page='bombas-de-calor',
  title='Bombas de calor ar-água em Lisboa | MDM',
  desc='Instalação e manutenção de bombas de calor ar-água para águas quentes e aquecimento em Lisboa. Técnicos certificados F-gas e eletricista da casa.',
  eyebrow='Bombas de calor · Lisboa', h1='Bombas de calor ar-\u2060água em Lisboa',
  lead='Águas quentes e aquecimento para casas e pequenos negócios, com a instalação, a ligação ao quadro e a manutenção feitas pela mesma equipa desde 1991.',
  hero=('pic', 'bomba-moradia', 'Bomba de calor ar-água instalada pela MDM numa moradia', 'Bomba de calor ar-\u2060água · moradia'),
  types_title='Bombas de calor ar-\u2060água, da escolha ao quadro elétrico.',
  types=[('Águas quentes', 'Aquece a água da casa de banho e da cozinha a partir do ar exterior, com um depósito próprio.'),
         ('Águas quentes e aquecimento', 'O mesmo equipamento aquece a água e a casa, quando a casa e o uso o justificam. Vemos consigo se é o seu caso.'),
         ('Ligação ao quadro', 'O circuito próprio e a proteção no quadro elétrico ficam feitos pelo nosso eletricista, na mesma obra.')],
  feature=dict(id='parte-eletrica', eyebrow='A parte elétrica', title='A parte que outros subcontratam, nós fazemos.',
   body=['Uma bomba de calor precisa muitas vezes de um circuito próprio e de proteção no quadro elétrico. Se o quadro for antigo, pode ser preciso adaptá-lo antes da instalação.',
         'Como temos eletricista certificado na equipa, a avaliação do quadro faz parte da visita técnica e a ligação é feita na mesma obra. Não fica à espera de um segundo profissional.'],
   aside=('svg', 'heatpump-large.svg')),
  included=[('Visita técnica', 'Vemos o espaço, o local da unidade exterior e do depósito, e o quadro elétrico.'),
            ('Equipamento dimensionado', 'Escolhido para a casa e para o consumo de água quente, não pelo catálogo.'),
            ('Técnicos certificados', 'Certificação para gases fluorados (F-gas).'),
            ('Circuito elétrico', 'Feito pelo nosso eletricista certificado, na mesma obra.'),
            ('Arranque e explicação', 'Deixamos o sistema a funcionar e explicamos as regulações.'),
            ('Manutenção', 'Revisões pela mesma equipa, pontuais ou com contrato anual.')],
  gallery=[('bomba-varanda-deposito', 'Bomba de calor com depósito de água quente numa varanda', 'Bomba de calor e depósito', 'Varanda de apartamento')],
  faq=[('Qual é a diferença entre uma bomba de calor ar-\u2060água e um ar condicionado?', 'O ar condicionado aquece ou arrefece o ar da divisão. A bomba de calor ar-\u2060água aquece água: a das torneiras, guardada num depósito, e, num sistema combinado, também a do aquecimento da casa.'),
       ('A bomba de calor precisa de obras elétricas?', 'Muitas vezes precisa de um circuito próprio no quadro. Como temos eletricista certificado na equipa, tratamos disso na mesma obra.'),
       ('A bomba de calor precisa de manutenção?', 'Sim. Uma revisão periódica mantém o rendimento do equipamento. A mesma equipa que instala faz a manutenção.')],
  form_title='Peça o orçamento da sua bomba de calor.',
  form_lead='Sem compromisso. Fotografias do espaço técnico e do quadro elétrico ajudam-nos a preparar a visita.',
  service_type='Instalação de bombas de calor ar-água', offers=['Bomba de calor para águas quentes', 'Bomba de calor para águas quentes e aquecimento', 'Manutenção de bombas de calor'],
  related=['ar-condicionado-lisboa', 'instalacoes-eletricas-lisboa', 'manutencao-assistencia-avac-lisboa']),

 'manutencao-assistencia-avac-lisboa': dict(
  nav='Manutenção e assistência', servico='Manutenção ou avaria', page='manutencao',
  title='Manutenção e assistência técnica AVAC em Lisboa | MDM',
  desc='Assistência técnica e contratos de manutenção de ar condicionado e bombas de calor em Lisboa, para casas, lojas, condomínios e empresas.',
  eyebrow='Manutenção e assistência · Lisboa', h1='Manutenção e assistência técnica AVAC em Lisboa',
  lead='Contratos anuais de manutenção preventiva e reparação de avarias em ar condicionado, bombas de calor e ventilação. Para casas, lojas, condomínios e empresas, desde 1991.',
  hero=('pic', 'manutencao-conduta', 'Técnico da MDM em manutenção de uma unidade de condutas no teto', 'Manutenção de unidade de condutas · teto falso'),
  types_title='Três formas de trabalharmos consigo.',
  included_title='O que está incluído.',
  types=[('Contrato anual', 'Visitas programadas de manutenção preventiva, com relatório, para casas, lojas, condomínios e empresas.'),
         ('Assistência a avarias', 'Quando um equipamento deixa de funcionar ou funciona mal. Uma fotografia por WhatsApp ajuda o técnico a saber o que levar.'),
         ('Revisão pontual', 'Uma limpeza e verificação completas, por exemplo antes do verão ou do inverno.')],
  feature=dict(id='visita', eyebrow='Numa visita de manutenção', title='O que fazemos, equipamento a equipamento.',
   body=['Limpamos filtros e unidades interiores, verificamos o funcionamento das unidades exteriores, os escoamentos e as ligações elétricas, e registamos o que encontrámos.',
         'Quando o equipamento está sujeito a verificação de fugas de gases fluorados, fazemos a verificação e deixamos o registo. Se for preciso reparar, explicamos o quê e porquê antes de avançar.'],
   aside=('pic', 'reparacao-unidade', 'Unidade exterior aberta para reparação', 'Reparação de unidade exterior')),
  included=[('Relatório de cada visita', 'O que foi feito, o estado de cada equipamento e o que recomendamos.'),
            ('Técnicos certificados', 'Certificação para gases fluorados (F-gas) e eletricista certificado na equipa.'),
            ('Várias marcas', 'Trabalhamos com MIDEA, Mitsubishi Electric, Daikin e France Air, entre outras.'),
            ('Ar condicionado e bombas de calor', 'Split, multi-split, conduta, cassete e bombas de calor ar-\u2060água.'),
            ('Ventilação', 'Extração e renovação de ar em cozinhas, lojas e espaços técnicos.'),
            ('A mesma equipa', 'Quem instala é quem mantém: conhece o equipamento e o local.')],
  gallery=[('cassete-manutencao', 'Manutenção do filtro de uma cassete de teto', 'Cassete de teto', 'Limpeza de filtros'),
           ('unidade-aberta-manutencao', 'Unidade exterior aberta durante uma intervenção técnica', 'Unidade exterior', 'Intervenção técnica'),
           ('unidade-daikin', 'Unidade Daikin numa sala técnica', 'Unidade Daikin', 'Sala técnica'),
           ('cobertura-unidades-solar', 'Unidade exterior Midea na cobertura de um edifício', 'Unidade exterior Midea', 'Cobertura de edifício')],
  faq=[('Com que frequência deve ser feita a manutenção?', 'Recomendamos pelo menos uma revisão por ano. Em lojas, restaurantes ou equipamentos com muito uso, pode justificar-se mais do que uma.'),
       ('Fazem contratos de manutenção para casas e lojas?', 'Sim. Fazemos contratos anuais de manutenção preventiva para casas, lojas, condomínios e empresas, com visitas programadas e relatório.'),
       ('Como peço assistência para uma avaria?', 'Ligue 218 935 050 (2ª a 6ª, 8h às 17h) ou envie uma fotografia da avaria por WhatsApp para o 910 307 579. Com a fotografia, o técnico percebe logo o que levar.'),
       ('A que marcas dão assistência?', 'MIDEA, Mitsubishi Electric, Daikin e France Air, entre outras.')],
  form_title='Peça assistência ou uma proposta de manutenção.',
  form_lead='Diga-nos que equipamentos tem e onde. Se for uma avaria, uma fotografia ajuda.',
  service_type='Manutenção e assistência técnica AVAC', offers=['Contrato anual de manutenção preventiva', 'Assistência a avarias', 'Revisão pontual'],
  related=['ar-condicionado-lisboa', 'bombas-de-calor-lisboa', 'ventilacao-lisboa']),

 'instalacoes-eletricas-lisboa': dict(
  nav='Instalações elétricas', servico='Instalação elétrica', page='eletricidade',
  title='Eletricista e instalações elétricas em Lisboa | MDM',
  desc='Quadros elétricos, circuitos e alimentação para ar condicionado e bombas de calor em Lisboa. Eletricista certificado, desde 1991.',
  eyebrow='Instalações elétricas · Lisboa', h1='Instalações elétricas e quadros em Lisboa',
  lead='Quadros elétricos, circuitos novos e a alimentação de ar condicionado e bombas de calor, feitos pelo nosso eletricista certificado. Em Lisboa desde 1991.',
  hero=('pic', 'quadro-eletrico', 'Técnico da MDM a intervir num quadro elétrico com autómato e disjuntores', 'Intervenção em quadro elétrico'),
  types_title='O trabalho elétrico que fazemos.',
  types=[('Quadros elétricos', 'Montagem, alteração e identificação de quadros, com as proteções adequadas a cada circuito.'),
         ('Circuitos para climatização', 'Alimentação própria para ar condicionado, multi-split e bombas de calor, feita na mesma obra da instalação.'),
         ('Novos pontos e circuitos', 'Tomadas, iluminação e circuitos novos em casas, lojas e escritórios.')],
  feature=dict(id='climatizacao', eyebrow='Frio, calor e eletricidade', title='Uma só equipa para o equipamento e para o quadro.',
   body=['Num ar condicionado ou numa bomba de calor, a parte elétrica decide muito: a potência disponível, o circuito próprio e a proteção certa no quadro.',
         'Como o eletricista certificado faz parte da mesma equipa, vê o quadro na visita técnica e faz a ligação na mesma obra. Um só orçamento, um só responsável.'],
   aside=('svg', 'eletrico.svg')),
  included_title='O que está incluído.',
  included=[('Eletricista certificado', 'O trabalho elétrico é feito e acompanhado por eletricista certificado.'),
            ('Proteções adequadas', 'Disjuntores e diferenciais escolhidos para cada circuito.'),
            ('Quadros identificados', 'Cada circuito fica identificado no quadro.'),
            ('Casas, lojas e escritórios', 'Trabalho em habitação e em pequenos espaços comerciais.')],
  gallery=[],
  faq=[('Fazem só a parte elétrica, sem ar condicionado?', 'Sim. Fazemos quadros, circuitos e novos pontos também em obras sem climatização.'),
       ('O meu quadro aguenta um ar condicionado ou uma bomba de calor?', 'Depende da potência contratada e do estado do quadro. Verificamos isso na visita técnica, antes do orçamento.'),
       ('Trabalham em lojas e escritórios?', 'Sim, em habitação e em espaços comerciais na Grande Lisboa.')],
  form_title='Peça o orçamento do trabalho elétrico.',
  form_lead='Sem compromisso. Uma fotografia do quadro elétrico ajuda-nos a preparar a visita.',
  service_type='Instalações elétricas', offers=['Quadros elétricos', 'Circuitos para ar condicionado e bombas de calor', 'Novos pontos e circuitos'],
  related=['ar-condicionado-lisboa', 'bombas-de-calor-lisboa', 'manutencao-assistencia-avac-lisboa']),

 'ventilacao-lisboa': dict(
  nav='Ventilação', servico='Ventilação', page='ventilacao',
  title='Ventilação e extração em Lisboa | MDM',
  desc='Instalação e manutenção de ventilação e extração para casas, cozinhas, lojas e restaurantes em Lisboa. Condutas, grupos de extração e revisões.',
  eyebrow='Ventilação · Lisboa', h1='Ventilação e extração em Lisboa',
  lead='Extração e renovação de ar para casas, cozinhas, lojas e restaurantes. Condutas, grupos de extração e revisões, pela nossa própria equipa desde 1991.',
  hero=('pic', 'ventilacao-fachada', 'Condutas de ventilação montadas pela MDM na fachada de um edifício', 'Condutas de ventilação · fachada de edifício'),
  types_title='Ventilação à medida do espaço.',
  types=[('Casas', 'Extração em cozinhas e casas de banho, para tirar humidade e cheiros.'),
         ('Lojas e restaurantes', 'Extração de cozinhas e renovação de ar em espaços com público.'),
         ('Condutas e grupos de extração', 'Montagem e substituição de condutas, ventiladores e grupos de extração.')],
  feature=None,
  included=[('Visita técnica', 'Vemos o espaço, o percurso possível das condutas e a saída do ar.'),
            ('Montagem completa', 'Condutas, grupos de extração, grelhas e ligação elétrica.'),
            ('Eletricista na equipa', 'A alimentação e o comando dos ventiladores ficam feitos na mesma obra.'),
            ('Manutenção', 'Limpeza e revisão de ventiladores e filtros, pontual ou com contrato.')],
  gallery=[('ventilacao-cobertura', 'Unidade de ventilação e condutas instaladas numa cobertura em Lisboa', 'Ventilação e condutas', 'Cobertura, Lisboa')],
  faq=[('Fazem extração para cozinhas de restaurantes?', 'Sim. Instalamos e mantemos extração em cozinhas de restaurantes e noutros espaços comerciais.'),
       ('A ventilação precisa de manutenção?', 'Sim. Ventiladores e filtros acumulam sujidade e perdem rendimento. Fazemos a limpeza e a revisão, pontualmente ou com contrato.'),
       ('Também tratam da parte elétrica?', 'Sim. A alimentação e o comando dos ventiladores são feitos pelo nosso eletricista certificado.')],
  form_title='Peça o orçamento da ventilação.',
  form_lead='Sem compromisso. Fotografias do espaço e do sítio por onde pode sair o ar ajudam-nos a preparar a visita.',
  service_type='Ventilação e extração', offers=['Extração em cozinhas e casas de banho', 'Ventilação de lojas e restaurantes', 'Condutas e grupos de extração'],
  related=['manutencao-assistencia-avac-lisboa', 'instalacoes-eletricas-lisboa', 'ar-condicionado-lisboa']),
}

NAMES = {'ar-condicionado-lisboa': 'Ar condicionado', 'bombas-de-calor-lisboa': 'Bombas de calor ar-\u2060água',
         'manutencao-assistencia-avac-lisboa': 'Manutenção e assistência técnica', 'instalacoes-eletricas-lisboa': 'Instalações elétricas',
         'ventilacao-lisboa': 'Ventilação'}
