// Pipeline de testes: extrai os <script> do index.html → verificação de sintaxe → testes da lógica pura (RI).
const fs = require('fs'), path = require('path'), vm = require('vm'), assert = require('assert');
const root = path.join(__dirname, '..');
const html = fs.readFileSync(path.join(root, 'index.html'), 'utf8');
const core = html.match(/<script id="ri-core">([\s\S]*?)<\/script>/);
const ui = html.match(/<script>\n\/\* ═══ Interface([\s\S]*?)<\/script>\s*<\/body>/);
assert(core && ui, 'não encontrei os dois blocos <script> esperados');
fs.writeFileSync(path.join(__dirname, 'core_extracted.js'), core[1]);
fs.writeFileSync(path.join(__dirname, 'ui_extracted.js'), '/* ═══ Interface' + ui[1]);
new vm.Script(core[1], { filename: 'core.js' });
new vm.Script('/* ═══ Interface' + ui[1], { filename: 'ui.js' });
console.log('sintaxe OK — core', core[1].length, 'chars · ui', ui[1].length, 'chars');
assert(!/Claude|Anthropic|Opus|Sonnet/i.test(html), 'identificadores de modelo no artefacto');
assert(!/https?:\/\/(cdn|fonts\.|unpkg|jsdelivr)/i.test(html), 'dependências externas (tem de funcionar offline)');
assert(html.includes('2024/573') && html.includes('145/2017') && !html.includes('842/2006') && !html.includes('56/2011'), 'referências legais desatualizadas');
assert(html.includes('Manuel Domingos Melancia') && !html.includes('Domingues'), 'nome legal errado');

const RI = require(path.join(__dirname, 'core_extracted.js'));
let n = 0; const t = (nome, fn) => { try { fn(); n++; } catch (e) { console.error('✗', nome, '\n  ', e.message); process.exit(1); } };

t('duração e formato', () => { assert.strictEqual(RI.duracao('10:30', '16:30'), 360); assert.strictEqual(RI.fmtHM(360), '6:00'); assert.strictEqual(RI.fmtHM(65), '1:05'); assert.strictEqual(RI.duracao('16:30', '10:30'), -360); assert.strictEqual(RI.duracao('', '10:00'), null); });
t('números PT (vírgula) e arredondamento', () => { assert.strictEqual(RI.num('1,200'), 1.2); assert.strictEqual(RI.num('3.6'), 3.6); assert.strictEqual(RI.round2(1.005), 1.01); assert.strictEqual(RI.fmtNum(7.5), '7,50'); assert.strictEqual(RI.fmtEur(12.5), '12,50 €'); });
t('GWP e t CO2e', () => { assert.strictEqual(RI.gwp('R410A'), 2088); assert.strictEqual(RI.co2e('3,6', 2088), 7.52); assert.strictEqual(RI.co2e('1.2', 2088), 2.51); assert.strictEqual(RI.gwp('Outro', '1500'), 1500); assert.strictEqual(RI.gwp('Outro', ''), null); assert.strictEqual(RI.co2e('', 2088), null); });
t('verificação de fugas — art. 5.º (limiares e periodicidades)', () => {
  assert.strictEqual(RI.verificacao('R410A', 2.51, false, false).obrigatoria, false);
  assert.deepStrictEqual([RI.verificacao('R410A', 7.52, false, false).meses, RI.verificacao('R410A', 7.52, false, true).meses], [12, 24]);
  assert.deepStrictEqual([RI.verificacao('R410A', 60, false, false).meses, RI.verificacao('R410A', 60, false, true).meses], [6, 12]);
  assert.deepStrictEqual([RI.verificacao('R404A', 520, false, false).meses, RI.verificacao('R404A', 520, false, true).meses], [3, 6]);
  assert.match(RI.verificacao('R404A', 520, false, false).texto, /deteção de fugas obrigatório/);
  assert.strictEqual(RI.verificacao('R32', 8, true, false).obrigatoria, false);   // hermético < 10 t
  assert.strictEqual(RI.verificacao('R32', 12, true, false).obrigatoria, true);   // hermético ≥ 10 t
  assert.strictEqual(RI.verificacao('R290', 50, false, false).obrigatoria, false);
  assert.match(RI.verificacao('R22', 9, false, false).texto, /HCFC/);
  assert.match(RI.verificacao('R1234yf', 9, false, false).texto, /confirmar/i);
});
t('addMonths respeita fim de mês', () => { assert.strictEqual(RI.addMonths('2026-01-31', 1), '2026-02-28'); assert.strictEqual(RI.addMonths('2028-01-31', 1), '2028-02-29'); assert.strictEqual(RI.addMonths('2026-09-07', 12), '2027-09-07'); assert.strictEqual(RI.addMonths('2026-11-30', 3), '2027-02-28'); assert.strictEqual(RI.addMonths('', 1), null); });
t('numeração, slug e nome de ficheiro', () => { assert.strictEqual(RI.numero(2026, 'al', 42), 'RI-2026-AL-0042'); assert.strictEqual(RI.slug('Condomínio Ação & Cia, Lda.'), 'Condominio Acao Cia Lda'); assert.strictEqual(RI.ficheiro({ numero: 'RI-2026-AL-0042', cliente: { nome: 'Paula Lemos' }, data_inicio: '2026-09-07' }), 'RI-2026-AL-0042 Paula Lemos 2026-09-07'); });
t('NIF, telefone, email, matrícula', () => { assert.strictEqual(RI.nifValido('502644761'), true); assert.strictEqual(RI.nifValido('502644760'), false); assert.strictEqual(RI.telValido('910 307 579'), true); assert.strictEqual(RI.telValido('+351218935050'), true); assert.strictEqual(RI.telValido('123'), false); assert.strictEqual(RI.telFmt('910307579'), '910 307 579'); assert.strictEqual(RI.emailValido('a@b.pt'), true); assert.strictEqual(RI.emailValido('ab.pt'), false); assert.strictEqual(RI.matriculaNorm('aa0000'), 'AA-00-00'); assert.strictEqual(RI.matriculaValida('00-AA-00'), true); assert.strictEqual(RI.matriculaValida('AAA-000'), false); });
t('materiais: totais e linhas sem preço', () => { const r = RI.totais([{ qty: '2', preco: '10' }, { qty: '1,5', preco: '4' }]); assert.deepStrictEqual([r.total, r.incompleto], [26, false]); const s = RI.totais([{ qty: '2', preco: '10' }, { qty: '1', preco: '' }]); assert.deepStrictEqual([s.total, s.incompleto], [20, true]); assert.strictEqual(RI.linhaTotal({ qty: '3', preco: '99', garantia: true }), 0); });

const cfg = { codigo: 'AL', tecnico_nome: 'Abdul Latif', tecnico_cert: 'PT-123', tecnico_oc: 'APIRAC', matricula: 'AA-00-00', email_escritorio: 'mdmassist@mdmassist.com' };
const base = () => { const r = RI.novo(cfg, 2026, 42, new Date(2026, 8, 7, 10, 32)); Object.assign(r.cliente, { nome: 'Paula Lemos', morada: 'Passeio Vila Expo 15, 7.º E, Lisboa', contacto: '910307579' }); r.tipo_intervencao = 'Contrato'; r.cliente.contrato = 'C-2026-01'; r.descricao = 'Manutenção preventiva contratual; verificação de fugas'; r.hora_inicio = '10:30'; r.hora_fim = '16:30'; r.equipamentos = [{ id: 'e1', categoria: 'Split / multi-split', marca: 'Mitsubishi Electric', modelo: 'MXZ-4F72VF', serie: 'SN123', refrigerante: 'R410A', carga_kg: '3,6', hermetico: false, detecao: false }]; r.deslocacao.taxa = 'nao'; return r; };
const bloq = (r) => RI.bloqueantes(RI.validar(r, '2026-09-07')).map(e => e.campo);
t('novo relatório: número, hora arredondada aos 5 min, data', () => { const r = RI.novo(cfg, 2026, 42, new Date(2026, 8, 7, 10, 32)); assert.strictEqual(r.numero, 'RI-2026-AL-0042'); assert.strictEqual(r.hora_inicio, '10:30'); assert.strictEqual(r.data_inicio, '2026-09-07'); assert.strictEqual(r.estado, 'rascunho'); });
t('relatório simples válido: zero bloqueantes', () => { assert.deepStrictEqual(bloq(base()), []); });
t('obrigatórios gerais', () => { const r = base(); r.cliente.nome = ''; r.descricao = 'curto'; r.hora_fim = '09:00'; r.tipo_intervencao = ''; assert.deepStrictEqual(bloq(r).sort(), ['cliente.nome', 'descricao', 'hora_fim', 'tipo_intervencao']); });
t('data futura bloqueia; > 31 dias avisa', () => { const r = base(); r.data_inicio = '2026-09-08'; assert(bloq(r).includes('data_inicio')); r.data_inicio = '2026-07-01'; assert(!bloq(r).includes('data_inicio')); assert(RI.validar(r, '2026-09-07').some(e => e.campo === 'data_inicio' && !e.bloq)); });
t('sugestão modelo → refrigerante e aviso se divergente', () => { assert.strictEqual(RI.sugestaoRefrigerante('MXZ-4F72VF'), 'R410A'); assert.strictEqual(RI.sugestaoRefrigerante('MXZ-3F54VG'), 'R32'); const r = base(); r.equipamentos[0].refrigerante = 'R32'; assert(RI.validar(r, '2026-09-07').some(e => e.campo === 'equipamentos.0.refrigerante' && !e.bloq)); });
t('F-gas: verificação sem fuga completa', () => { const r = base(); r.houve_gas = true; Object.assign(r.fgas, { equip_id: 'e1', motivo: 'Verificação periódica', verificacao: 'sem_fuga', metodo: ['Detetor eletrónico'], ficha_oc: true }); assert.deepStrictEqual(bloq(r), []); const c = RI.fgasCalc(r); assert.strictEqual(c.t, 7.52); assert.strictEqual(c.verif.meses, 12); assert.strictEqual(c.proxima, '2027-09-07'); assert.strictEqual(c.reverif, null); assert.strictEqual(RI.sugestaoProxima(r), '2027-09-07'); });
t('F-gas: recarga exige verificação, reparação, ensaio e origem', () => { const r = base(); r.houve_gas = true; Object.assign(r.fgas, { equip_id: 'e1', motivo: 'Reparação de fuga', verificacao: 'nao', qty_add: '1,2' }); let b = bloq(r); assert(b.includes('fgas.verificacao') && b.includes('fgas.motivo_nao') && b.includes('fgas.ensaio_final') && b.includes('fgas.origem'));
  Object.assign(r.fgas, { verificacao: 'fuga', metodo: ['Espuma / bolhas'], fuga_local: 'Ligação flare UE', fuga_reparada: 'nao' }); r.obra_concluida = 'sim'; b = bloq(r); assert(b.includes('fgas.qty_add') && b.includes('obra_concluida'));
  Object.assign(r.fgas, { fuga_reparada: 'sim', reparacao_desc: 'Reaperto de porca flare; vácuo 30 min', ensaio_final: 'ok', origem: 'Virgem' }); b = bloq(r); assert.deepStrictEqual(b, []); const c = RI.fgasCalc(r); assert.strictEqual(c.reverif, '2026-10-07'); assert.strictEqual(c.proxima, '2027-09-07'); assert.strictEqual(RI.sugestaoProxima(r), '2026-10-07'); assert.strictEqual(RI.cargaFinal(r), 3.6);
  Object.assign(r.fgas, { origem: 'Regenerado', origem_inst: '', origem_cert: '' }); assert(bloq(r).includes('fgas.origem_inst')); });
t('F-gas: R22 nunca pode ser carregado nem reintroduzido', () => { const r = base(); r.equipamentos[0].refrigerante = 'R22'; r.houve_gas = true; Object.assign(r.fgas, { equip_id: 'e1', motivo: 'Reparação de fuga', verificacao: 'fuga', metodo: ['Detetor eletrónico'], fuga_local: 'Schrader', fuga_reparada: 'sim', reparacao_desc: 'Substituição de Schrader', ensaio_final: 'ok', qty_add: '1,2', origem: 'Virgem' }); const E = RI.validar(r, '2026-09-07'); assert(E.some(e => e.campo === 'fgas.qty_add' && e.bloq && /R22/.test(e.msg)));
  Object.assign(r.fgas, { qty_add: '0', qty_rec: '2', destino_rec: 'Reintroduzido no mesmo equipamento' }); assert(bloq(r).includes('fgas.destino_rec')); r.fgas.destino_rec = 'Garrafa de recuperação → regeneração'; assert.deepStrictEqual(bloq(r).filter(k => k.startsWith('fgas')), []);
  assert(bloq(Object.assign(base(), { materiais: [{ designacao: 'Gás R22', origem: 'Stock', qty: '1' }] })).includes('materiais.0')); });
t('F-gas: desmantelamento exige recuperação e medidas; ≥ 500 t avisa deteção', () => { const r = base(); r.houve_gas = true; Object.assign(r.fgas, { equip_id: 'e1', motivo: 'Desmantelamento', verificacao: 'nao', motivo_nao: 'Desmantelamento total', qty_rec: '0' }); let b = bloq(r); assert(b.includes('fgas.qty_rec') && b.includes('fgas.desmant_medidas')); Object.assign(r.fgas, { qty_rec: '3,4', destino_rec: 'Garrafa de recuperação → destruição', desmant_medidas: 'Recolha total do gás para garrafa e envio para destruição.' }); assert.deepStrictEqual(bloq(r), []); assert.strictEqual(RI.cargaFinal(r), 0);
  const g = base(); g.equipamentos[0].categoria = 'Chiller'; g.equipamentos[0].carga_kg = '300'; assert(RI.validar(g, '2026-09-07').some(e => e.campo === 'equipamentos.0.detecao' && !e.bloq)); });
t('F-gas: dados do equipamento e certificado obrigatórios', () => { const r = base(); r.houve_gas = true; r.equipamentos[0].serie = ''; r.fgas.tecnico_cert = ''; Object.assign(r.fgas, { equip_id: 'e1', motivo: 'Verificação periódica', verificacao: 'sem_fuga', metodo: ['Detetor eletrónico'] }); const b = bloq(r); assert(b.includes('equipamentos.gas') && b.includes('fgas.tecnico_cert')); r.equipamentos[0].serie = 'ILEGÍVEL'; r.fgas.tecnico_cert = 'X'; assert(bloq(r).includes('fotos')); r.fotos = [{ id: 'f1', categoria: 'Chapa de características' }]; assert.deepStrictEqual(bloq(r), []); });
t('deslocação e conclusão', () => { const r = base(); r.deslocacao = { taxa: 'sim', matricula: 'xx', km: '' }; assert.deepStrictEqual(bloq(r).sort(), ['deslocacao.km', 'deslocacao.matricula']); const s = base(); s.obra_concluida = 'nao'; s.pendentes = ''; s.proxima_visita = '2026-09-07'; assert.deepStrictEqual(bloq(s).sort(), ['pendentes', 'proxima_visita']); });
t('orçamento: sim exige n.º, não exige desvio', () => { const r = base(); r.conforme_orcamento = 'sim'; assert(bloq(r).includes('orcamento_numero')); r.conforme_orcamento = 'nao'; assert(bloq(r).includes('orcamento_desvio')); });
t('SHA-256 e hash canónico (ignora aceitação do cliente e imagens)', () => { assert.strictEqual(RI.sha256('abc'), 'ba7816bf8f01cfea414140de5dae2223b00361a396177a9cb410ff61f20015ad'); assert.strictEqual(RI.sha256(''), 'e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855'); assert.strictEqual(RI.sha256('Olá, Manuel Domingos Melancia — ção'), RI.sha256('Olá, Manuel Domingos Melancia — ção')); const r = base(); const h1 = RI.hash(r); r.aceitacao = { nome: 'X', png: 'data:...' }; r.fotos = [{ id: 'f', categoria: 'Antes', dataUrl: 'data:big' }]; const h2 = RI.hash(r); assert.strictEqual(h1.length, 64); assert.notStrictEqual(h1, h2); r.fotos[0].dataUrl = 'data:other'; assert.strictEqual(RI.hash(r), h2); r.descricao += ' alterado'; assert.notStrictEqual(RI.hash(r), h2); });
t('email: resumo curto, mailto válido, CC ao cliente', () => { const r = base(); r.cliente.email = 'paula@example.pt'; r.houve_gas = true; Object.assign(r.fgas, { equip_id: 'e1', motivo: 'Verificação periódica', verificacao: 'sem_fuga', metodo: ['Detetor eletrónico'] }); r.materiais = [{ designacao: 'Filtro', qty: '2', unidade: 'un', preco: '' }]; r.hash = RI.hash(r); const m = RI.emailResumo(r, cfg); assert(m.href.startsWith('mailto:mdmassist%40mdmassist.com?cc=paula%40example.pt&subject=')); assert(m.body.length <= 1700); assert(m.body.includes('7,52 t CO2e') && m.body.includes('valores a definir')); assert.strictEqual(m.subject, 'Relatório de Intervenção RI-2026-AL-0042 — Paula Lemos — 07/09/2026'); });
console.log('✅', n, 'grupos de testes passaram');
